tasks:
  - name: Install Terraform
    init: |
      # Define the desired Terraform version
      TERRAFORM_VERSION="1.11.4" # <--- **UPDATE THIS TO THE LATEST VERSION**

      # Define the download URL for Linux AMD64 (most common Gitpod architecture)
      TERRAFORM_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      echo "Downloading Terraform version ${TERRAFORM_VERSION}..."
      wget ${TERRAFORM_URL} -O terraform.zip

      echo "Unzipping Terraform..."
      unzip terraform.zip

      echo "Moving Terraform to /usr/local/bin/..."
      # Use sudo to move the binary to a directory in the system's PATH
      sudo mv terraform /usr/local/bin/

      echo "Cleaning up downloaded files..."
      rm terraform.zip

      echo "Terraform installed successfully!"

      # Indicate that the Terraform installation task is complete
      gp sync-done install-terraform

    # Optional: Add command to verify installation after init
    command: |
      echo "Verifying Terraform installation:"
      terraform --version